trigger: none

pool: default

stages:
 - stage: source
   jobs:
     - job: FetchCode
       steps:
         - checkout: self

     - job: TerraformToolInstaller
       steps:
       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'

 - stage: ValidateAndInit
   jobs:
     - job: validateInit
       steps:
       - task: TerraformTask@5
         displayName: 'terraform init'
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'service'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'
           backendAzureRmStorageAccountName: 'storage'
           backendAzureRmContainerName: 'container'
           backendAzureRmKey: 'dev.tfstate'
       - task: TerraformTask@5
         displayName: terraform validate
         inputs:
           provider: 'azurerm'
           command: 'validate'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'


 - stage: LintingAndSecurity
   jobs:
     - job: SecurityCheck
       steps:
       - task: CmdLine@2
         displayName: 'Run TFlint'
         inputs:
           script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            tflint .
       - task: Bash@3
         displayName: 'Run tfsec'
         inputs:
           targetType: 'inline'
           script: |
             curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
             tfsec .
       - task: Bash@3
         displayName: 'run checkov'
         inputs:
           targetType: 'inline'
           script: |
             pip install checkov
             checkov -d .

 - stage: InfraPlanning
   jobs:
     - job: Plan
       steps:
       - task: TerraformTask@5
         displayName: 'terraform init'
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'service'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'
           backendAzureRmStorageAccountName: 'storage'
           backendAzureRmContainerName: 'container'
           backendAzureRmKey: 'dev.tfstate'

       - task: TerraformTask@5
         displayName: 'terraform plan'
         inputs:
           provider: 'azurerm'
           command: 'plan'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'

     - job: ManualValidation
       dependsOn: plan
       pool: server
       steps:
       - task: ManualValidation@1
         displayName: 'manual validation'
         inputs:
           notifyUsers: 'useremail@gmail.com'
           instructions: 'Please review the Terraform plan and approve'

 - stage: InfraDeployment
   jobs:
     - job: InfraCreation
       steps:
       - task: TerraformTask@5
         displayName: 'terraform init'
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'
           backendServiceArm: 'service'
           backendAzureRmStorageAccountName: 'storage'
           backendAzureRmContainerName: 'container'
           backendAzureRmKey: 'dev.tfstate'

       - task: TerraformTask@5
         displayName: 'terraform apply'
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: '$(System.DefaultWorkingDirectory)/resource/infrastructure'
